# Configurações Globais do Serviço
settings:
  log_level: "info"        # debug, info, warn, error
  delay_before_move: 2s    # Tempo de espera para garantir que o ficheiro não está bloqueado
  max_workers: 3           # Número de goroutines simultâneas para mover ficheiros

# Lista de pastas a monitorizar
monitors:
  - name: "Pasta Teste"
    source_path: "/Users/marcomartinelli/Desktop/teste"
    recursive: true  # Monitora todas as subpastas

    # Regras específicas para esta pasta
    rules:
      - name: "Documentos de Trabalho"
        extensions: [".pdf", ".docx", ".xlsx"]
        destination: "/Users/marcomartinelli/Desktop/teste/organized"
        conflict_strategy: "overwrite" # Opções: rename, overwrite, skip